apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-service
  labels:
    app: edge-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-service
  template:
    metadata:
      labels:
        app: edge-service
    spec:
      containers:
        - name: edge-service
          image: edge-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: edge-config-volume
              mountPath: /workspace/config
              readOnly: true
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: DASHBOARD_UI_URL
              value: "http://dashboard-ui"
            - name: REALISASI_UI_URL
              value: "http://realisasi-ui"
            - name: OPD_SERVICE_URL
              value: "http://opd-service"
            - name: PERENCANAAN_SERVICE_URL
              value: "http://perencanaan-service"
            - name: REALISASI_SERVICE_URL
              value: "http://realisasi-pemda-service"
            - name: MANRISK_OPD_SERVICE_URL
              value: "http://manrisk-opd-service"
            - name: SPRING_DATA_REDIS_HOST
              value: "kertaskerja-redis"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER_URI
              value: "http://keycloak.kertaskerja.local/realms/KabMadiun"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://keycloak.kertaskerja.local/realms/KabMadiun"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_ID
              value: "edge-service"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_KEYCLOAK_CLIENT_SECRET
              value: "wfIn5MSSA5f5Nu0eqCiNxHwbJN6p1PES"
            - name: SPRING_WEB_CORS_ALLOWED_ORIGIN_PATTERNS
              value: "http://*.kertaskerja.local"
            - name: SPRING_WEB_CORS_ALLOWED_METHODS
              value: "GET, POST, PUT, DELETE, OPTIONS"
            - name: SPRING_WEB_CORS_ALLOW_CREDENTIALS
              value: "true"
      volumes:
        - name: edge-config-volume
          configMap:
            name: edge-service-config
