apiVersion: apps/v1
kind: Deployment
metadata:
  name: perencanaan-service
  labels:
    app: perencanaan-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perencanaan-service
  template:
    metadata:
      labels:
        app: perencanaan-service
    spec:
      containers:
        - name: perencanaan-service
          image: perencanaan-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 8081
          env:
            - name: DB_URL
              value: "root:root@tcp(kertaskerja-mysql:3306)/ekak_db?parseTime=true"
            - name: DB_USER
              value: "root"
            - name: host
              value: "0.0.0.0"
            - name: port
              value: "8081"
            - name: KEYCLOAK_ISSUER
              value: "http://keycloak.kertaskerja.local/realms/KabMadiun"
            - name: KEYCLOAK_JWKS_URL
              value: "http://keycloak.kertaskerja.local/realms/KabMadiun/protocol/openid-connect/certs"
