apiVersion: apps/v1
kind: Deployment
metadata:
  name: realisasi-pemda-service
  labels:
    app: realisasi-pemda-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: realisasi-pemda-service
  template:
    metadata:
      labels:
        app: realisasi-pemda-service
    spec:
      containers:
        - name: realisasi-pemda-service
          image: realisasi-pemda-service:latest
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              value: "http://keycloak.kertaskerja.local/realms/KabMadiun"
          volumeMounts:
            - name: realisasi-pemda-config-volume
              mountPath: /workspace/config
      volumes:
        - name: realisasi-pemda-config-volume
          configMap:
            name: realisasi-pemda-config
