apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  labels:
    db: kertaskerja-mysql
data:
  init.sql: |
    CREATE DATABASE ekak_db;
    CREATE DATABASE keycloak_db;

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kertaskerja-mysql
  labels:
    db: kertaskerja-mysql
spec:
  selector:
    matchLabels:
      db: kertaskerja-mysql
  template:
    metadata:
      labels:
        db: kertaskerja-mysql
    spec:
      containers:
        - name: kertaskerja-mysql
          image: mysql:8.0.39
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-initdb
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-initdb
          configMap:
            name: mysql-config
            items:
              - key: init.sql
                path: init.sql

---

apiVersion: v1
kind: Service
metadata:
  name: kertaskerja-mysql
  labels:
    db: kertaskerja-mysql
spec:
  type: ClusterIP
  selector:
    db: kertaskerja-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
