apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    db: kertaskerja-postgres
data:
  init.sql: |
    CREATE DATABASE kertaskerja_kepegawaian;
    CREATE DATABASE kertaskerja_opd;
    CREATE DATABASE kertaskerja_urusan;
    CREATE DATABASE kertaskerja_bidang_urusan;
    CREATE DATABASE kertaskerja_program;
    CREATE DATABASE kertaskerja_kegiatan;
    CREATE DATABASE kertaskerja_subkegiatan;
    CREATE DATABASE kertaskerja_keycloak;
    CREATE DATABASE manajemen_risiko;
    CREATE DATABASE kertaskerja_realisasi_pemda;

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: kertaskerja-postgres
  labels:
    db: kertaskerja-postgres
spec:
  selector:
    matchLabels:
      db: kertaskerja-postgres
  template:
    metadata:
      labels:
        db: kertaskerja-postgres
    spec:
      containers:
        - name: kertaskerja-postgres
          image: postgres:16-alpine
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi
          volumeMounts:
            - mountPath: /docker-entrypoint-initdb.d
              name: postgres-config-volume
      volumes:
        - name: postgres-config-volume
          configMap:
            name: postgres-config

---

apiVersion: v1
kind: Service
metadata:
  name: kertaskerja-postgres
  labels:
    db: kertaskerja-postgres
spec:
  type: ClusterIP
  selector:
    db: kertaskerja-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
