apiVersion: apps/v1
kind: Deployment
metadata:
  name: kertaskerja-redis
  labels:
    db: kertaskerja-redis
spec:
  selector:
    matchLabels:
      db: kertaskerja-redis
  template:
    metadata:
      labels:
        db: kertaskerja-redis
    spec:
      containers:
        - name: kertaskerja-redis
          image: redis:alpine
          env:
            - name: REDIS_PORT
              value: "6379"
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 200m
              memory: 100Mi

---

apiVersion: v1
kind: Service
metadata:
  name: kertaskerja-redis
  labels:
    db: kertaskerja-redis
spec:
  type: ClusterIP
  selector:
    db: kertaskerja-redis
  ports:
  - protocol: TCP
    port: 6379
    targetPort: 6379
