apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keycloak.yml

configMapGenerator:
  - name: kertaskerja-keycloak-config
    files:
      - realm-export.json
    options:
      labels:
        app: kertaskerja-keycloak
